### ISSUE TITLE
Docker-compose for zoraxy portainer template

### ISSUE THREAD

**Issue by barto95100** [fredarro/template-portainer#1]
docker-compose.yml
```
version: '3.3'
services:
  zoraxy-docker:
    image: ghcr.io/barto95100/zoraxy-dns-challenge:v3.0.3
    container_name: ${name_container}
    ports:
      - 80:80
      - 443:443
      - ${ports}:8000
    volumes:
      - ${folder}/conf:/opt/zoraxy/config/
    environment:
      ARGS: '-fastgeoip=true'
```

template:
```

{
			"type": 3,
			"title": "zoraxy",
			"name": "zoraxy",
			"categories": ["test"],
			"description": "zoraxy",
			"logo": "https://www.myqnap.org/wp-content/uploads/zoraxy-logo.png",
			"env": [
				{
					"label": "port",
					"name": "port",
					"default": "8000"
				},
				{
					"label": "name_container",
					"name": "name_container",
					"default": "zoraxy-v3.0.3-dns-challenge"
				},
				{
					"label": "folder",
					"name": "folder",
					"default": "/home/docker/zoraxy"
				},
			],
			"platform": "linux",
			"repository": {
				"stackfile": "zoraxy/docker-compose.yml",
				"url": "https://github.com/fredarro/template-portainer"
			}
		}
```
